Update index.ts: add expect: “100-continue”
Doris Stream Load Issue:

at async /app/packages/shared/dist/src/server/instrumentation/index.js:47:28
2025-07-31T05:32:39.525Z error Max attempts reached for observations record. Dropping record.
2025-07-31T05:32:39.525Z error Max attempts reached for observations record. Dropping record.
2025-07-31T05:32:39.525Z error Max attempts reached for observations record. Dropping record.
2025-07-31T05:32:39.526Z error Stream load failed
2025-07-31T05:32:39.526Z error DorisWriter.writeToDoris Error: Stream load failed after 3 attempts: Stream load failed: There is no 100-continue header
2025-07-31T05:32:39.526Z error DorisWriter.flush traces Stream load failed after 3 attempts: Stream load failed: There is no 100-continue header
Error: Stream load failed after 3 attempts: Stream load failed: There is no 100-continue header
at DorisClient.insert (/app/packages/shared/dist/src/server/doris/client.js:387:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async DorisWriter.writeToDoris (/app/worker/dist/services/DorisWriter/index.js:151:9)
at async DorisWriter.flush (/app/worker/dist/services/DorisWriter/index.js:101:13)
at async Promise.all (index 0)
at async /app/worker/dist/services/DorisWriter/index.js:71:13
at async /app/packages/shared/dist/src/server/instrumentation/index.js:47:28
2025-07-31T05:32:39.526Z error Max attempts reached for traces record. Dropping record.